export const EmployeeData = [
  {
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    role: 'Software Engineer',
    department: 'IT',
    status: 'active',
  },
  {
    fullName: 'Priya Mehta',
    email: 'priya.mehta@example.com',
    role: 'HR Manager',
    department: 'HR',
    status: 'active',
  },
  {
    fullName: 'Rohan Verma',
    email: 'rohan.verma@example.com',
    role: 'Marketing Executive',
    department: 'Marketing',
    status: 'inactive',
  },
  {
    fullName: 'Simran Kaur',
    email: 'simran.kaur@example.com',
    role: 'Finance Analyst',
    department: 'Finance',
    status: 'active',
  },
  {
    fullName: 'Aditya Gupta',
    email: 'aditya.gupta@example.com',
    role: 'Sales Executive',
    department: 'Sales',
    status: 'active',
  },
  {
    fullName: 'Neha Singh',
    email: 'neha.singh@example.com',
    role: 'UI/UX Designer',
    department: 'IT',
    status: 'inactive',
  },
  {
    fullName: 'Karan Malhotra',
    email: 'karan.malhotra@example.com',
    role: 'HR Coordinator',
    department: 'HR',
    status: 'active',
  },
  {
    fullName: 'Ishita Bose',
    email: 'ishita.bose@example.com',
    role: 'Digital Marketer',
    department: 'Marketing',
    status: 'active',
  },
  {
    fullName: 'Rahul Nair',
    email: 'rahul.nair@example.com',
    role: 'Accountant',
    department: 'Finance',
    status: 'inactive',
  },
  {
    fullName: 'Tanvi Deshmukh',
    email: 'tanvi.deshmukh@example.com',
    role: 'Sales Manager',
    department: 'Sales',
    status: 'active',
  },
];
